### ISSUE TITLE
你好，现在插件好像出现了一些问题，方便更新一下吗？

### ISSUE THREAD

**Issue by wager98** [czp3009/LagGridBroadcaster#2]
当玩家网格US超标之后，输入!laggrids send  15指令，过一会提示这个回复 object reference not set to an instance of an object，如果没有超标，就挺正常的，请问是什么原因呢？
![QQ截图20210328140952](https://user-images.githubusercontent.com/54735972/112744072-4a26ef80-8fcf-11eb-9585-4d1063e42279.png)

**Comment by czp3009** [comment]
无法复现此问题，请提供完整的 stacktrace

panweijie13 ***@***.***> 于 2021年3月28日周日 下午2:10写道：

**Comment by wager98** [comment]
完整的 stacktrace文件？可以详细说明一下那个文件吗？或者有没有其他联系方式，我直接联系你吧

**Comment by czp3009** [comment]
当出现错误时, 查看服务端的控制台输出, 并将异常堆栈复制黏贴出来.

不建议使用除 issue 以外的方式报告程序问题, 那样无法对有着同样问题的人提供帮助.

如果有别的事想要联系我, 可以通过我的电子邮箱, 详见我的 GitHub 主页.

panweijie13 ***@***.***> 于2021年3月28日周日 下午4:43写道：

**Comment by wager98** [comment]
21:24:42.2223 [INFO]   CommandManager: Player 快递员 ran command '!laggrids send 15'
21:24:42.2223 [INFO]   Chat:  (to 快递员): Started profiling grids, result in 15s
21:24:53.1322 [INFO]   Chat: [Faction:285057001792920149] 奥利给，干了！！: AZ
21:24:57.2238 [INFO]   Chat:  (to 快递员): Profiling finish in 549ticks
21:24:57.2238 [INFO]   LagGridBroadcasterCommands: Measure results saved to file
21:24:57.2238 [ERROR]  LagGridBroadcasterCommands: System.NullReferenceException: Object reference not set to an instance of an object.
   at LagGridBroadcaster.LagGridBroadcasterCommands.<>c__DisplayClass10_2.<OnProfilerRequestFinished>b__13(MyPlayer it) in C:\Users\czp\Documents\RiderProjects\LagGridBroadcaster\LagGridBroadcaster\LagGridBroadcasterCommands.cs:line 213
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at LagGridBroadcaster.LagGridBroadcasterCommands.<>c__DisplayClass10_1.<OnProfilerRequestFinished>b__11(MeasureResult measureResult) in C:\Users\czp\Documents\RiderProjects\LagGridBroadcaster\LagGridBroadcaster\LagGridBroadcasterCommands.cs:line 212
   at System.Linq.Enumerable.WhereListIterator`1.MoveNext()
   at System.Linq.Enumerable.<TakeIterator>d__25`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at LagGridBroadcaster.LagGridBroadcasterCommands.OnProfilerRequestFinished(BaseProfilerResult`1 result, UInt64 ticks) in C:\Users\czp\Documents\RiderProjects\LagGridBroadcaster\LagGridBroadcaster\LagGridBroadcasterCommands.cs:line 204
   at LagGridBroadcaster.LagGridBroadcasterCommands.<>c__DisplayClass6_0.<<Send>b__0>d.MoveNext() in C:\Users\czp\Documents\RiderProjects\LagGridBroadcaster\LagGridBroadcaster\LagGridBroadcasterCommands.cs:line 90
System.NullReferenceException: Object reference not set to an instance of an object.
   at LagGridBroadcaster.LagGridBroadcasterCommands.<>c__DisplayClass10_2.<OnProfilerRequestFinished>b__13(MyPlayer it) in C:\Users\czp\Documents\RiderProjects\LagGridBroadcaster\LagGridBroadcaster\LagGridBroadcasterCommands.cs:line 213
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at LagGridBroadcaster.LagGridBroadcasterCommands.<>c__DisplayClass10_1.<OnProfilerRequestFinished>b__11(MeasureResult measureResult) in C:\Users\czp\Documents\RiderProjects\LagGridBroadcaster\LagGridBroadcaster\LagGridBroadcasterCommands.cs:line 212
   at System.Linq.Enumerable.WhereListIterator`1.MoveNext()
   at System.Linq.Enumerable.<TakeIterator>d__25`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at LagGridBroadcaster.LagGridBroadcasterCommands.OnProfilerRequestFinished(BaseProfilerResult`1 result, UInt64 ticks) in C:\Users\czp\Documents\RiderProjects\LagGridBroadcaster\LagGridBroadcaster\LagGridBroadcasterCommands.cs:line 204
   at LagGridBroadcaster.LagGridBroadcasterCommands.<>c__DisplayClass6_0.<<Send>b__0>d.MoveNext() in C:\Users\czp\Documents\RiderProjects\LagGridBroadcaster\LagGridBroadcaster\LagGridBroadcasterCommands.cs:line 90
21:24:57.2238 [INFO]   Chat:  (to 快递员): Error occured: Object reference not set to an instance of an object.

**Comment by wager98** [comment]
你好，请问这个是什么情况呢？

**Comment by czp3009** [comment]
为了解决此问题, 请在下一次出错时, 把上图中的 LagGridsBroadcastMeasureResult.xml 文件也复制黏贴出来, 这个文件默认在服务端的 Instance 文件夹下.

**Comment by wager98** [comment]
好的，麻烦您了，请查收

**Comment by wager98** [comment]
[LagGridBroadcasterMeasureResult.zip](https://github.com/czp3009/LagGridBroadcaster/files/6217420/LagGridBroadcasterMeasureResult.zip)

**Comment by czp3009** [comment]
这个问题应该是由于错误的阵营和玩家数据造成的, 分析数据与处理需要一定时间.

**Comment by wager98** [comment]
请问有没有办法可以解决呢？

**Comment by czp3009** [comment]
解决之后会在 issue 中通知, 不能解决也会通知

**Comment by wager98** [comment]
21:50:55.7173 [ERROR]  PlayerAccountModule: Exception creating account for ZERUO System.NullReferenceException: Object reference not set to an instance of an object.
   at Essentials.PlayerAccountModule.GenerateAccount(IPlayer player) in C:\build\workspace\Torch_Essentials_master\Essentials\PlayerAccountModule.cs:line 153

**Comment by wager98** [comment]
![11](https://user-images.githubusercontent.com/54735972/112755430-3bfac280-9013-11eb-9085-fbe2a93b3f93.png)

**Comment by wager98** [comment]
你好，是关于这个回复吗？

**Comment by czp3009** [comment]
你的服务端的 Essential  插件的设置能截图看看嘛

**Comment by wager98** [comment]
![1](https://user-images.githubusercontent.com/54735972/112755614-f8ed1f00-9013-11eb-9019-defcfbfc2788.png)

**Comment by wager98** [comment]
![2](https://user-images.githubusercontent.com/54735972/112755642-24700980-9014-11eb-8347-6d08fe8cdded.png)

**Comment by wager98** [comment]
![3](https://user-images.githubusercontent.com/54735972/112755658-39e53380-9014-11eb-98c3-8b42721f727d.png)

**Comment by wager98** [comment]
![4](https://user-images.githubusercontent.com/54735972/112755668-423d6e80-9014-11eb-9520-06c40dfe02dd.png)

**Comment by wager98** [comment]
![5](https://user-images.githubusercontent.com/54735972/112755706-76b12a80-9014-11eb-8670-a6c9d1122e23.png)

**Comment by wager98** [comment]
您好，麻烦了，您看下这个插件设置是否导致与这个插件冲突了

**Comment by czp3009** [comment]
应该没有冲突.

我再研究一下.

**Comment by wager98** [comment]
好的，谢谢了

**Comment by czp3009** [comment]
> 请问有没有办法可以解决呢？

已修复此问题, 重启服务端以更新插件.

若问题重新出现请再次打开此 issue.
